import fs from 'node:fs';

const date = process.env.SEO_AUDIT_DATE || '2026-09-07';
const dir = process.env.SEO_AUDIT_DIR || `seo-audit/${date}`;
const NA = 'NOT AVAILABLE — DATA ACCESS REQUIRED';
const base = 'https://kujo.robertdevore.com';

const quote = value => `"${String(value ?? '').replaceAll('"', '""')}"`;
const csv = (name, rows) => {
  const file = `${dir}/${name}.csv`;
  const existing = fs.readFileSync(file, 'utf8').split(/\r?\n/)[0].split(',');
  const fields = [...new Set([...existing, ...rows.flatMap(Object.keys)])];
  fs.writeFileSync(file, `${fields.join(',')}\n${rows.map(row => fields.map(field => quote(row[field])).join(',')).join('\n')}\n`);
};
const md = (name, body) => fs.writeFileSync(`${dir}/${name}.md`, `${body}\n`);
const readJson = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const audit = phase => readJson(`${dir}/raw/npm-audit-${phase}.json`).metadata.vulnerabilities;
const lighthouse = phase => readJson(`${dir}/raw/${phase}-lighthouse-home.json`);
const baseline = readJson(`${dir}/baseline-summary.json`);
const after = readJson(`${dir}/after-summary.json`);
const beforeAudit = audit('before');
const afterAudit = audit('after');
const beforeLh = lighthouse('baseline');
const afterLh = lighthouse('after');

const performanceRow = (phase, report) => {
  const requests = report.audits['network-requests'].details.items;
  const bytes = type => requests.filter(request => request.resourceType === type).reduce((sum, request) => sum + (request.transferSize || 0), 0);
  return {
    phase, url: report.finalDisplayedUrl || report.finalUrl, template: 'home', run_date: report.fetchTime,
    environment: 'Chrome headless; Lighthouse default mobile simulated throttling', lighthouse_version: report.lighthouseVersion,
    html_bytes: bytes('Document'), css_bytes: bytes('Stylesheet'), js_bytes: bytes('Script'), image_bytes: bytes('Image'),
    font_bytes: bytes('Font'), requests: requests.length, lcp_ms: report.audits['largest-contentful-paint'].numericValue,
    inp_ms: NA, cls: report.audits['cumulative-layout-shift'].numericValue,
    ttfb_ms: report.audits['server-response-time']?.numericValue ?? 'not reported',
    source: `${dir}/raw/${phase}-lighthouse-home.json`, performance_score: report.categories.performance.score * 100,
    accessibility_score: report.categories.accessibility.score * 100, best_practices_score: report.categories['best-practices'].score * 100,
    lighthouse_seo_score: report.categories.seo.score * 100, tbt_ms: report.audits['total-blocking-time'].numericValue,
    notes: 'Single lab observation; not field CWV and not evidence of ranking impact.'
  };
};

csv('performance', [performanceRow('baseline', beforeLh), performanceRow('after', afterLh)]);
csv('content-audit', [{phase:'after',url:`${base}/`,source_file:'course.json + lessons + pages',page_type:'course',primary_purpose:'Teach Kujo through executable lessons and projects',search_intent:'educational',target_audience:'Experienced software developers',central_entity:'Kujo programming language',primary_query_theme:'Kujo course',supporting_topics:'runtime; capabilities; replay; agents; MCP; RAG',h1:'Learn Kujo by building reliable software',heading_structure:'one H1; ordered course stages',word_count:'page-level values retained in after.csv',first_hand_signals:'verified examples and generated evidence receipts',content_gap:'Search Console and learner-query evidence unavailable',recommended_action:'Preserve content; use measured query data for future refinements'}]);
csv('keyword-map', [{phase:'after',url:`${base}/`,primary_topic:'Kujo programming language course',primary_entity:'Kujo',search_intent:'learn',primary_query_theme:'learn Kujo programming language',secondary_queries:'Kujo tutorial; Kujo capabilities; Kujo replay; Kujo agents; Kujo MCP; Kujo RAG',related_entities:'Kujo VM; Model Context Protocol; retrieval-augmented generation',relevant_questions:'How do I learn Kujo? How do capabilities and deterministic replay work?',content_gap:'No query-volume or impression data',recommended_action:'Validate themes in GSC and Bing before changing page targeting'}]);
csv('search-rankings', [{query:'Kujo programming language course',search_engine:NA,date,country:NA,device:NA,page_found:NA,observed_position_or_range:NA,competing_results:NA,rich_features:NA,ai_result_presence:NA,evidence:'No first-party search-performance account was supplied',limitations:NA}]);
csv('ai-search-benchmark', [{question:'What is the Kujo programming language and where can I learn it?',platform:NA,date,domain_appeared:NA,domain_cited:NA,cited_url:NA,citation_context:NA,citation_order:NA,competing_domains:NA,accurate_representation:NA,content_gap:'Run controlled provider benchmarks when access and a measurement protocol are available',evidence:'No provider session was supplied; results were not fabricated',limitations:NA}]);
csv('issues', [
  {id:'SEC-01',phase:'before/after',category:'dependency security',severity:'P1',affected_urls:'build/deploy toolchain',affected_count:beforeAudit.high,evidence:'npm-audit-before.json; dependency-tree-after.txt; npm-audit-after.json',expected_benefit:'Remove the high-severity Sharp advisory from the development toolchain',confidence:'high',difficulty:'low',recommended_action:'Keep Wrangler exactly pinned at 4.131.0 or later patched releases after verification',owner:'course maintainer',status:'fixed'},
  {id:'MEASURE-01',phase:'after',category:'measurement',severity:'P2',affected_urls:'site-wide',affected_count:0,evidence:'data-availability.md',expected_benefit:'Measure actual discovery and citation outcomes',confidence:'high',difficulty:'requires account access',recommended_action:'Provide GSC, Bing, analytics, field CWV, and controlled AI-answer data',owner:'site owner',status:`blocked: ${NA}`},
  {id:'HOST-01',phase:'after',category:'host alias',severity:'P3',affected_urls:'https://www.kujo.robertdevore.com/',affected_count:1,evidence:'raw/after-edge.json',expected_benefit:'Optional alternate-host coverage',confidence:'high',difficulty:'owner decision',recommended_action:'Configure only if the optional www hostname is intentionally supported',owner:'site owner',status:'optional; canonical hostname is healthy'}
]);

md('methodology', `# Methodology — ${date}\n\nScope: repository, generated static output, and all ${after.pages} sitemap URLs for ${base}. The immutable before baseline was captured before the dependency edit in \`raw/baseline-output.tar.gz\`, \`baseline.csv\`, \`baseline-summary.json\`, dependency checksums, npm audit JSON, production response receipts, redirect/crawler probes, and a home-page Lighthouse report.\n\nThe implementation updated the exact Wrangler development dependency only. Afterward, a clean \`npm ci\` install, dependency-tree inspection, npm audit, full course verification/build, Cloudflare deployment dry run, a second full crawl, edge probes, and a comparable Lighthouse run were recorded. The crawl validates generated and live status, titles, descriptions, canonicals, headings, links, indexability, images, schema parsing/purpose, crawl depth, and sitemap membership. User-agent probes do not prove verified crawler-IP access.\n\nLighthouse is a single lab observation under simulated mobile throttling. It is not field Core Web Vitals or causal evidence of ranking improvement. Search performance, analytics, bot logs, and AI citations are reported as unavailable rather than estimated. No composite SEO or AI-readiness score is invented.`);
md('data-availability', `# Data availability\n\nAvailable: repository source; generated output; ${after.pages} canonical production responses; local and production metadata/schema/link inventories; redirect and crawler user-agent probes; npm audit receipts; dependency resolution; build verification; a comparable home-page Lighthouse lab run.\n\n- Google Search Console performance/index coverage: ${NA}\n- Bing Webmaster Tools performance/index coverage: ${NA}\n- Analytics, conversions, and referral data: ${NA}\n- Verified crawler-IP and full CDN access logs: ${NA}\n- CrUX/RUM field LCP, INP, and CLS: ${NA}\n- Controlled ChatGPT, Claude, and Perplexity citation benchmarks: ${NA}\n- Backlink/authority dataset: ${NA}`);
md('research-sources', `# Current primary guidance — retrieved ${date}\n\n- https://developers.google.com/search/docs/essentials — Google Search Essentials; satisfy technical requirements and spam policies while creating useful content.\n- https://developers.google.com/search/docs/essentials/technical — Google technical requirements for index eligibility.\n- https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls — Google canonicalization guidance; align redirects, canonicals, sitemaps, and internal links.\n- https://developers.google.com/search/docs/appearance/structured-data/sd-policies — Google structured-data policies; markup must represent visible content and eligibility is not guaranteed.\n- https://developers.google.com/search/docs/appearance/core-web-vitals — Google Core Web Vitals guidance; field data is distinct from lab observations.\n- https://www.bing.com/webmasters/help/how-to-create-a-robots-txt-file-cb7c31ec — Bing robots.txt guidance.\n- https://www.bing.com/webmasters/help/bing-webmaster-guidelines-30fba23a — Bing Webmaster Guidelines.\n- https://www.bing.com/webmasters/help/indexnow-0z209wby — Bing IndexNow documentation; submission is discovery notification, not a ranking guarantee.\n- https://schema.org/Course — Schema.org Course vocabulary.\n- https://developers.openai.com/api/docs/bots — OpenAI crawler documentation; OAI-SearchBot, GPTBot, and ChatGPT-User have distinct purposes. Existing training policy was preserved.`);
md('changes', `# Changes\n\n- Exact-pinned Wrangler from 4.129.0 to 4.131.0.\n- Updated the lockfile resolution from Miniflare 5.20260903.0-alpha / Sharp 0.35.2 to Miniflare 5.20260910.0-alpha / Sharp 0.35.4.\n- Made the existing audit scripts accept a dated audit directory so new evidence does not overwrite the prior audit.\n- Rebuilt and validated the full static course output. Public output is byte-identical to the baseline except for regenerated verification timing evidence.\n- Preserved site content, metadata, schema, canonical URLs, crawler policy, and WebMCP behavior.`);
md('before-after', `# Before / after\n\n| Check | Baseline | After |\n|---|---:|---:|\n| High-severity npm vulnerabilities | ${beforeAudit.high} | ${afterAudit.high} |\n| Total npm vulnerabilities | ${beforeAudit.total} | ${afterAudit.total} |\n| Wrangler | 4.129.0 | 4.131.0 |\n| Miniflare | 5.20260903.0-alpha | 5.20260910.0-alpha |\n| Sharp | 0.35.2 | 0.35.4 |\n| Canonical pages crawled | ${baseline.pages} | ${after.pages} |\n| Missing or duplicate titles | ${baseline.missingTitles + baseline.duplicateTitles} | ${after.missingTitles + after.duplicateTitles} |\n| Missing or duplicate descriptions | ${baseline.missingDescriptions + baseline.duplicateDescriptions} | ${after.missingDescriptions + after.duplicateDescriptions} |\n| Missing canonicals / H1 problems | ${baseline.missingCanonicals + baseline.h1Problems} | ${after.missingCanonicals + after.h1Problems} |\n| Broken internal/external destinations | ${baseline.brokenInternalDestinations.length + baseline.brokenExternalDestinations.length} | ${after.brokenInternalDestinations.length + after.brokenExternalDestinations.length} |\n| Orphans / pages deeper than three clicks | ${baseline.orphans + baseline.deeperThanThree} | ${after.orphans + after.deeperThanThree} |\n| Schema parse/purpose errors | ${baseline.schemaParseErrors + baseline.schemaPurposeMismatches} | ${after.schemaParseErrors + after.schemaPurposeMismatches} |\n| Missing image alt/dimensions | ${baseline.missingAlt + baseline.missingDimensions} | ${after.missingAlt + after.missingDimensions} |\n| Production failures | ${baseline.productionFailures} | ${after.productionFailures} |\n| Home Lighthouse SEO | ${beforeLh.categories.seo.score * 100} | ${afterLh.categories.seo.score * 100} |\n| Home Lighthouse accessibility | ${beforeLh.categories.accessibility.score * 100} | ${afterLh.categories.accessibility.score * 100} |\n\nThe security finding is fixed without changing course content or public behavior. Lighthouse performance remained 61/100 in both single lab runs; that is an observation, not a regression claim. Field CWV, rankings, and AI citations remain ${NA}.`);
md('unresolved', `# Unresolved and bounded claims\n\n- Search Console, Bing Webmaster Tools, analytics, field CWV, verified bot logs, and controlled AI citation data are ${NA}; no visibility uplift is claimed.\n- The optional \`www.kujo.robertdevore.com\` hostname did not resolve during edge probes. It is not advertised, linked, or canonicalized by the site.\n- Lighthouse performance/best-practices scores are lab observations and include live edge behavior. No site-content change was justified by this dependency-focused audit.\n- No unresolved dependency-security finding remains in the installed tree.`);
md('recommendations', `# Recommendations\n\n- By 2026-09-29 (7 days): confirm the repository security alert closes after the pushed lockfile is processed; recrawl the canonical sitemap if production content changes.\n- By 2026-10-20 (28 days): export GSC and Bing page/query/index coverage if visibility measurement is desired.\n- By 2026-11-21 (60 days): compare field Core Web Vitals only if enough real-user data exists; do not infer field performance from a single Lighthouse run.\n- By 2026-12-21 (90 days): run controlled AI-answer/citation benchmarks with saved provider, model, locale, answer, citation, and timestamp evidence.\n- Keep deployment tooling exact-pinned and require \`npm ci\`, \`npm audit --audit-level=high\`, the full course verification, and a Wrangler dry run before future upgrades.`);
md('executive-summary', `# PASS WITH RECOMMENDATIONS\n\nAudit date: ${date}. The high-severity development dependency finding is fixed: Wrangler 4.131.0 resolves Miniflare 5.20260910.0-alpha and patched Sharp 0.35.4, and npm now reports zero vulnerabilities. A clean install, complete ${after.pages}-page crawl, full course verification/build, dependency inspection, and deployment dry run pass.\n\nTechnical SEO/AI-search readiness checks are clean across all ${after.pages} canonical pages: zero missing/duplicate titles or descriptions, missing canonicals, H1 problems, broken linked destinations, crawl-depth/orphan issues, image alt/dimension gaps, schema parse/purpose errors, or production failures. Lighthouse SEO and accessibility are 100/100 before and after. Public output is unchanged apart from regenerated verification timing evidence.\n\nNo ranking, field-CWV, or AI-citation improvement is claimed because the required platform data is ${NA}. The optional www alias remains unconfigured and does not affect the canonical hostname.`);
