import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve('output');const files=[];function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,item.name);if(item.isDirectory())walk(p);else files.push(p);}}walk(root);
const htmlFiles=files.filter(p=>p.endsWith('.html'));const routes=new Map();for(const file of htmlFiles){const route='/'+path.relative(root,file).replaceAll(path.sep,'/').replace(/index\.html$/,'');routes.set(route,fs.readFileSync(file,'utf8'));}
const localRefs=[];for(const [route,html] of routes){assert.equal((html.match(/<h1(?:\s|>)/g)||[]).length,1,route+' h1');assert.match(html,/<html lang="en"/);assert.match(html,/<main id="main"|<main[^>]+id="main"/);assert.ok(!html.includes('{{'),route+' unresolved placeholder');assert.ok(!html.includes('```'),route+' unrendered fence');assert.ok(!html.includes('&lt;p class='),route+' unrendered authored HTML');const canonical=html.match(/<link rel="canonical" href="([^"]+)"/);assert.ok(canonical);assert.ok(canonical[1].startsWith('https://kujo.robertdevore.com/'));if(route.startsWith("/404")){assert.match(html,/noindex,follow/);}else {const blocks=[...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].map(m=>JSON.parse(m[1]));assert.ok(blocks.length);assert.ok(blocks[0]["author"]);if(route==="/")assert.equal(blocks[0]["@type"],"Course");if(route==="/about/")assert.equal(blocks[0]["@type"],"AboutPage");if(route!=="/")assert.equal(blocks[1]["@type"],"BreadcrumbList");}for(const m of html.matchAll(/(?:href|src)="([^"]+)"/g)){if(m[1].startsWith('/'))localRefs.push([route,m[1]]);}}
for(const [source,ref] of localRefs){const url=new URL(ref,'https://kujo.robertdevore.com');let file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');assert.ok(fs.existsSync(file),`${source}: missing ${ref}`);if(url.hash){const text=fs.readFileSync(file,'utf8');assert.ok(text.includes(`id="${url.hash.slice(1)}"`),`${source}: missing anchor ${ref}`);}}
const course=JSON.parse(fs.readFileSync('course.json'));assert.equal(course.lessons.length,40);for(const lesson of course.lessons){const html=routes.get('/course/'+lesson.slug+'/');assert.ok(html);assert.ok((html.match(/<pre><code/g)||[]).length>=6,lesson.slug+' code');assert.match(html,/data-complete=/);assert.match(html,/Break it and diagnose it/);assert.match(html,/Checkpoint/);assert.match(html,/Exercise/);}
const sitemap=fs.readFileSync('output/sitemap.xml','utf8');for(const route of routes.keys())if(!route.startsWith('/404'))assert.ok(sitemap.includes('https://kujo.robertdevore.com'+route),'sitemap '+route);
const search=JSON.parse(fs.readFileSync('output/assets/course-search.json'));assert.equal(search.length,40+JSON.parse(fs.readFileSync('pages.json')).length);assert.ok(fs.statSync('output/assets/js/course.js').size<16000);assert.ok(fs.statSync('output/assets/css/course.css').size<20000);assert.equal(fs.readFileSync('output/assets/social.png').subarray(1,4).toString(),'PNG');
fs.writeFileSync('evidence/site.json',JSON.stringify({date:new Date().toISOString().slice(0,10),htmlPages:htmlFiles.length,localReferences:localRefs.length,lessons:40,searchEntries:search.length,jsBytes:fs.statSync('output/assets/js/course.js').size,cssBytes:fs.statSync('output/assets/css/course.css').size,status:'passed'},null,2)+'\n');
console.log(`PASS: ${htmlFiles.length} pages, ${localRefs.length} internal references, 40 complete lesson structures, metadata, sitemap, assets, and size budgets`);
